=== FranciscaValenzuelaSalazar/full-project-java/testng.dtd
<!ELEMENT suite (listeners,test)>
<!ATTLIST suite name CDATA #REQUIRED>
<!ELEMENT listeners (listener)>
<!ELEMENT listener EMPTY>
<!ATTLIST listener class-name NMTOKEN #REQUIRED>
<!ELEMENT test (parameter,classes)>
<!ATTLIST test name CDATA #REQUIRED>
<!ATTLIST test enabled NMTOKEN #REQUIRED>
<!ELEMENT parameter EMPTY>
<!ATTLIST parameter name NMTOKEN #REQUIRED>
<!ATTLIST parameter value NMTOKEN #REQUIRED>
<!ELEMENT classes (class)>
<!ELEMENT class EMPTY>
<!ATTLIST class name NMTOKEN #REQUIRED>

=== FranciscaValenzuelaSalazar/full-project-java/testng.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "testng.dtd">
<suite name="Sample Test Suite">
	<listeners>
		<listener class-name="main.java.config.SuiteListener"/>
	</listeners>
	<test name="GoogleSearch" enabled="true">
		<parameter name="browserName" value="chrome" />
		<classes>
			<class name="test.java.main.GoogleTests"/>
		</classes>
	</test>
	<test name="GoogleTranslate" enabled="false">
		<parameter name="browserName" value="chrome" />
		<classes>
			<class name="test.java.main.GoogleTests" />
		</classes>
	</test>
</suite>
